# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crossing_mast.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='crossing_mast.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x63rossing_mast.proto\"\x8b\x01\n\nLogMessage\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\x05\x12 \n\x05level\x18\x02 \x01(\x0e\x32\x11.LogMessage.Level\x12\x11\n\tcomponent\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\")\n\x05Level\x12\x08\n\x04INFO\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\t\n\x05\x45RROR\x10\x02\"\x0e\n\x0cSetOnRequest\"\x0f\n\rSetOffRequest\"\"\n\rSetOnResponse\x12\x11\n\tsucceeded\x18\x01 \x01(\x08\"#\n\x0eSetOffResponse\x12\x11\n\tsucceeded\x18\x01 \x01(\x08\"$\n\x0eGetLogsRequest\x12\x12\n\nnum_events\x18\x01 \x01(\x05\"C\n\x0fGetLogsResponse\x12\x11\n\tsucceeded\x18\x01 \x01(\x08\x12\x1d\n\x08messages\x18\x02 \x03(\x0b\x32\x0b.LogMessage\"\x13\n\x11StreamLogsRequest2\xc7\x01\n\x0c\x43rossingMast\x12(\n\x05SetOn\x12\r.SetOnRequest\x1a\x0e.SetOnResponse\"\x00\x12*\n\x06SetOff\x12\r.SetOnRequest\x1a\x0f.SetOffResponse\"\x00\x12.\n\x07GetLogs\x12\x0f.GetLogsRequest\x1a\x10.GetLogsResponse\"\x00\x12\x31\n\nStreamLogs\x12\x12.StreamLogsRequest\x1a\x0b.LogMessage\"\x00\x30\x01\x62\x06proto3'
)



_LOGMESSAGE_LEVEL = _descriptor.EnumDescriptor(
  name='Level',
  full_name='LogMessage.Level',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INFO', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=122,
  serialized_end=163,
)
_sym_db.RegisterEnumDescriptor(_LOGMESSAGE_LEVEL)


_LOGMESSAGE = _descriptor.Descriptor(
  name='LogMessage',
  full_name='LogMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='LogMessage.date', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='LogMessage.level', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='component', full_name='LogMessage.component', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='LogMessage.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LOGMESSAGE_LEVEL,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=163,
)


_SETONREQUEST = _descriptor.Descriptor(
  name='SetOnRequest',
  full_name='SetOnRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=179,
)


_SETOFFREQUEST = _descriptor.Descriptor(
  name='SetOffRequest',
  full_name='SetOffRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=196,
)


_SETONRESPONSE = _descriptor.Descriptor(
  name='SetOnResponse',
  full_name='SetOnResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='succeeded', full_name='SetOnResponse.succeeded', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=232,
)


_SETOFFRESPONSE = _descriptor.Descriptor(
  name='SetOffResponse',
  full_name='SetOffResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='succeeded', full_name='SetOffResponse.succeeded', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=269,
)


_GETLOGSREQUEST = _descriptor.Descriptor(
  name='GetLogsRequest',
  full_name='GetLogsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_events', full_name='GetLogsRequest.num_events', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=307,
)


_GETLOGSRESPONSE = _descriptor.Descriptor(
  name='GetLogsResponse',
  full_name='GetLogsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='succeeded', full_name='GetLogsResponse.succeeded', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='messages', full_name='GetLogsResponse.messages', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=376,
)


_STREAMLOGSREQUEST = _descriptor.Descriptor(
  name='StreamLogsRequest',
  full_name='StreamLogsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=397,
)

_LOGMESSAGE.fields_by_name['level'].enum_type = _LOGMESSAGE_LEVEL
_LOGMESSAGE_LEVEL.containing_type = _LOGMESSAGE
_GETLOGSRESPONSE.fields_by_name['messages'].message_type = _LOGMESSAGE
DESCRIPTOR.message_types_by_name['LogMessage'] = _LOGMESSAGE
DESCRIPTOR.message_types_by_name['SetOnRequest'] = _SETONREQUEST
DESCRIPTOR.message_types_by_name['SetOffRequest'] = _SETOFFREQUEST
DESCRIPTOR.message_types_by_name['SetOnResponse'] = _SETONRESPONSE
DESCRIPTOR.message_types_by_name['SetOffResponse'] = _SETOFFRESPONSE
DESCRIPTOR.message_types_by_name['GetLogsRequest'] = _GETLOGSREQUEST
DESCRIPTOR.message_types_by_name['GetLogsResponse'] = _GETLOGSRESPONSE
DESCRIPTOR.message_types_by_name['StreamLogsRequest'] = _STREAMLOGSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LogMessage = _reflection.GeneratedProtocolMessageType('LogMessage', (_message.Message,), {
  'DESCRIPTOR' : _LOGMESSAGE,
  '__module__' : 'crossing_mast_pb2'
  # @@protoc_insertion_point(class_scope:LogMessage)
  })
_sym_db.RegisterMessage(LogMessage)

SetOnRequest = _reflection.GeneratedProtocolMessageType('SetOnRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETONREQUEST,
  '__module__' : 'crossing_mast_pb2'
  # @@protoc_insertion_point(class_scope:SetOnRequest)
  })
_sym_db.RegisterMessage(SetOnRequest)

SetOffRequest = _reflection.GeneratedProtocolMessageType('SetOffRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETOFFREQUEST,
  '__module__' : 'crossing_mast_pb2'
  # @@protoc_insertion_point(class_scope:SetOffRequest)
  })
_sym_db.RegisterMessage(SetOffRequest)

SetOnResponse = _reflection.GeneratedProtocolMessageType('SetOnResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETONRESPONSE,
  '__module__' : 'crossing_mast_pb2'
  # @@protoc_insertion_point(class_scope:SetOnResponse)
  })
_sym_db.RegisterMessage(SetOnResponse)

SetOffResponse = _reflection.GeneratedProtocolMessageType('SetOffResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETOFFRESPONSE,
  '__module__' : 'crossing_mast_pb2'
  # @@protoc_insertion_point(class_scope:SetOffResponse)
  })
_sym_db.RegisterMessage(SetOffResponse)

GetLogsRequest = _reflection.GeneratedProtocolMessageType('GetLogsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETLOGSREQUEST,
  '__module__' : 'crossing_mast_pb2'
  # @@protoc_insertion_point(class_scope:GetLogsRequest)
  })
_sym_db.RegisterMessage(GetLogsRequest)

GetLogsResponse = _reflection.GeneratedProtocolMessageType('GetLogsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETLOGSRESPONSE,
  '__module__' : 'crossing_mast_pb2'
  # @@protoc_insertion_point(class_scope:GetLogsResponse)
  })
_sym_db.RegisterMessage(GetLogsResponse)

StreamLogsRequest = _reflection.GeneratedProtocolMessageType('StreamLogsRequest', (_message.Message,), {
  'DESCRIPTOR' : _STREAMLOGSREQUEST,
  '__module__' : 'crossing_mast_pb2'
  # @@protoc_insertion_point(class_scope:StreamLogsRequest)
  })
_sym_db.RegisterMessage(StreamLogsRequest)



_CROSSINGMAST = _descriptor.ServiceDescriptor(
  name='CrossingMast',
  full_name='CrossingMast',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=400,
  serialized_end=599,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetOn',
    full_name='CrossingMast.SetOn',
    index=0,
    containing_service=None,
    input_type=_SETONREQUEST,
    output_type=_SETONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetOff',
    full_name='CrossingMast.SetOff',
    index=1,
    containing_service=None,
    input_type=_SETONREQUEST,
    output_type=_SETOFFRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetLogs',
    full_name='CrossingMast.GetLogs',
    index=2,
    containing_service=None,
    input_type=_GETLOGSREQUEST,
    output_type=_GETLOGSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StreamLogs',
    full_name='CrossingMast.StreamLogs',
    index=3,
    containing_service=None,
    input_type=_STREAMLOGSREQUEST,
    output_type=_LOGMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CROSSINGMAST)

DESCRIPTOR.services_by_name['CrossingMast'] = _CROSSINGMAST

# @@protoc_insertion_point(module_scope)
