# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import crossing_mast_pb2 as crossing__mast__pb2


class CrossingMastStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetOn = channel.unary_unary(
                '/CrossingMast/SetOn',
                request_serializer=crossing__mast__pb2.SetOnRequest.SerializeToString,
                response_deserializer=crossing__mast__pb2.SetOnResponse.FromString,
                )
        self.SetOff = channel.unary_unary(
                '/CrossingMast/SetOff',
                request_serializer=crossing__mast__pb2.SetOnRequest.SerializeToString,
                response_deserializer=crossing__mast__pb2.SetOffResponse.FromString,
                )
        self.GetLogs = channel.unary_unary(
                '/CrossingMast/GetLogs',
                request_serializer=crossing__mast__pb2.GetLogsRequest.SerializeToString,
                response_deserializer=crossing__mast__pb2.GetLogsResponse.FromString,
                )
        self.StreamLogs = channel.unary_stream(
                '/CrossingMast/StreamLogs',
                request_serializer=crossing__mast__pb2.StreamLogsRequest.SerializeToString,
                response_deserializer=crossing__mast__pb2.LogMessage.FromString,
                )


class CrossingMastServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetOn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrossingMastServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetOn': grpc.unary_unary_rpc_method_handler(
                    servicer.SetOn,
                    request_deserializer=crossing__mast__pb2.SetOnRequest.FromString,
                    response_serializer=crossing__mast__pb2.SetOnResponse.SerializeToString,
            ),
            'SetOff': grpc.unary_unary_rpc_method_handler(
                    servicer.SetOff,
                    request_deserializer=crossing__mast__pb2.SetOnRequest.FromString,
                    response_serializer=crossing__mast__pb2.SetOffResponse.SerializeToString,
            ),
            'GetLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogs,
                    request_deserializer=crossing__mast__pb2.GetLogsRequest.FromString,
                    response_serializer=crossing__mast__pb2.GetLogsResponse.SerializeToString,
            ),
            'StreamLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=crossing__mast__pb2.StreamLogsRequest.FromString,
                    response_serializer=crossing__mast__pb2.LogMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CrossingMast', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CrossingMast(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CrossingMast/SetOn',
            crossing__mast__pb2.SetOnRequest.SerializeToString,
            crossing__mast__pb2.SetOnResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CrossingMast/SetOff',
            crossing__mast__pb2.SetOnRequest.SerializeToString,
            crossing__mast__pb2.SetOffResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CrossingMast/GetLogs',
            crossing__mast__pb2.GetLogsRequest.SerializeToString,
            crossing__mast__pb2.GetLogsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/CrossingMast/StreamLogs',
            crossing__mast__pb2.StreamLogsRequest.SerializeToString,
            crossing__mast__pb2.LogMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
